# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('ComicCollectionTracker', '0002_auto_20170110_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCollection',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComicCollectionTracker.Collection')),
            ],
        ),
    ]
