# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComicCollectionTracker', '0004_auto_20170113_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultcollection',
            name='id',
        ),
        migrations.AlterField(
            model_name='defaultcollection',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
