# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComicCollectionTracker', '0005_auto_20170113_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='is_default',
        ),
    ]
