# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicCollectionTracker', '0008_auto_20170329_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='number',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='cover_url',
            field=models.CharField(max_length=500, verbose_name='Comicvine cover image URL'),
        ),
    ]
