# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicCollectionTracker', '0011_issue_comicvine_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='cover',
            field=models.CharField(default='1', max_length=100, verbose_name='Cover number or letter'),
        ),
    ]
