# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-14 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ComicCollectionTracker', '0012_auto_20170329_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='comicvine_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='on_sale_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
